# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
# concurrency:
#  group: "pages"
#  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            json-schema-for-humans
      - run: generate-schema-doc --config expand_buttons=true --config with_footer=false test.json docs/index.html
      - run: generate-schema-doc --config expand_buttons=true --config with_footer=false --config template_name=md test.json docs/schemaDocs.md

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Write File
        # You may pin to the exact commit or the version.
        # uses: DamianReeves/write-file-action@0a7fcbe1960c53fc08fe789fa4850d24885f4d84
        uses: DamianReeves/write-file-action@v1.2
        with:
          # The path to the file to write
          path: README.md
          # The contents of the file
          contents: |
            ### RTC Schema (Test) 
            - HTML Docs available [here](https://ashisha7i.github.io/test-json-schema/)
            - MarkDown Version available [here](docs/schemaDocs.md)
            ---
            __Generated on: ${{ steps.date.outputs.date }}__
          # The mode of writing to use: `overwrite`, `append`, or `preserve`.
          write-mode: overwrite
      
      
      - uses: EndBug/add-and-commit@v9
        with:
          add: .
          author_name: GitHub Actions
          message: Auto generated docs
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'docs'
          
      - name: Badges - Readme
        # You may pin to the exact commit or the version.
        # uses: pemtajo/badge-readme@3836d7866ca0765b3b4ff8f0f826037657a5f434
        uses: pemtajo/badge-readme@2.3.0
        with:
          # GitHub access token with Repo scope
          GH_TOKEN: ${{ github.token }}
          # Your GitHub repository
          REPOSITORY: ${{ github.repository }}
          # Add a commit message of your choice
          COMMIT_MESSAGE: Updated README with new badges
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
